Presentation/Trialcar.Web/Controllers/DealerCarController.cs
using Incite.Core.Domain;
using Incite.Core.Infrastructure;
using Incite.Services;
using Incite.Services.ViewModels;
using PagedList;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class DealerCarController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _dealerCarService;
        private readonly IPaymentService _paymentService;
        private readonly INotificationsService _notificationService;
        private readonly IUsersService _userService;
        #endregion

        #region Add car to compare
        public ActionResult AddToCompare()
        {
            dynamic showMessageString = string.Empty;
            try
            {

                System.Collections.Specialized.NameValueCollection nameValue = Request.Params;
                string dealerCarDetailId = nameValue.Get("dealerCarDetailId");
                System.Web.HttpContext context = System.Web.HttpContext.Current;
                DealerCarDetails carDetails = _dealerCarService.GetCarDetailById(int.Parse(dealerCarDetailId));

                if (carDetails.IsOnHold == false && carDetails.IsSold == false)
                {
                    if (context.Session["dealerCarDetailId"] == null)
                    {
                        //dealerIds[0] = dealerCarDetailId;
                        context.Session["dealerCarDetailId"] = dealerCarDetailId;
                        showMessageString = new
                        {
                            msg = "Added Car To Compare Successfully."
                        };
                    }
                    else
                    {
                        string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                        string[] strCarDetailIds = carDetailSession.Split(',');
                        if (strCarDetailIds.Count() < 3)
                        {
                            context.Session["dealerCarDetailId"] = context.Session["dealerCarDetailId"] + "," + dealerCarDetailId;
                            showMessageString = new
                            {
                                msg = "Add Car To Compare Successfully."
                            };
                        }
                        else
                        {
                            showMessageString = new
                            {
                                err = "Maximum 3 Cars Compared."
                            };
                        }

                    }
                }
                else
                {
                    showMessageString = new
                    {
                        err = "Sold Cars and Cars On Hold Cannot Be Compared."
                    };
                }

            }
            catch (Exception e)
            {
                showMessageString = new
                {
                    err = "Problem While Adding Car To Compare."
                };
            }

            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Remove car from compare
        public ActionResult RemoveToCompare()
        {
            dynamic showMessageString = string.Empty;
            try
            {
                System.Collections.Specialized.NameValueCollection nameValue = Request.Params;
                string dealerCarDetailId = nameValue.Get("dealerCarDetailId");

                System.Web.HttpContext context = System.Web.HttpContext.Current;

                if (context.Session["dealerCarDetailId"] != null)
                {
                    string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                    string[] strCarDetailIds = carDetailSession.Split(',');
                    if (strCarDetailIds.Contains(dealerCarDetailId))
                    {
                        var list = new List<string>(strCarDetailIds);
                        list.Remove(dealerCarDetailId);
                        strCarDetailIds = list.ToArray();
                    }
                    if (strCarDetailIds.Count() > 0)
                        context.Session["dealerCarDetailId"] = String.Join(",", strCarDetailIds);
                    else
                        context.Session["dealerCarDetailId"] = null;
                }
                showMessageString = new
                {
                    msg = "Remove Car From Compare Successfully."
                };
            }
            catch (Exception e)
            {
                showMessageString = new
                {
                    err = "Problem While Removing Car From Compare."
                };
            }

            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Car Compare
        public ActionResult Compare()
        {
            CheckCurrentUserSubscribedOrNot();

            System.Web.HttpContext context = System.Web.HttpContext.Current;
            IList<DealerCarDetails> carList = new List<DealerCarDetails>();
            IList<CarAccessories> carAccessories = _dealerCarService.GetCarAccessories();

            if (context.Session["dealerCarDetailId"] != null)
            {
                string carDetailSession = context.Session["dealerCarDetailId"].ToString();
                string[] strCarDetailIds = carDetailSession.Split(',');

                foreach (string strId in strCarDetailIds)
                {
                    if (int.Parse(strId) > 0)
                    {
                        DealerCarDetails model = _dealerCarService.GetCarDetailById(int.Parse(strId));
                        carList.Add(model);
                    }
                }
            }

            return View(Tuple.Create(carList, carAccessories));
        }
        #endregion


        public DealerCarController(IDealerCarService DealerCarService, IPaymentService PaymentService
            , INotificationsService notificationService
            , IUsersService userService)
        {
            _dealerCarService = DealerCarService;
            _paymentService = PaymentService;
            _notificationService = notificationService;
            _userService = userService;
        }
        // GET: DealerCar

        private void CheckCurrentUserSubscribedOrNot()
        {
            ViewBag.IsSubscribed = false;

            if (!Infrastructure.Authentication.IsAdmin)
            {
                var currentUser = _userService.GetAllUsers().Where(c => c.Id == Infrastructure.Authentication.CurrentUserId).FirstOrDefault();
                //ViewBag.IsSubscribed = currentUser.IsSubscribed;
                if (string.IsNullOrEmpty(currentUser.StripecustomerId))
                    ViewBag.IsSubscribed = false;
                else
                {
                    Customer customer = new Customer();
                    try
                    {
                        customer = _paymentService.GetCustomer(currentUser.StripecustomerId);
                        ViewBag.IsSubscribed = customer.Subscriptions.Count() > 0;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.IsSubscribed = false;
                    }

                }
            }
        }



        public string GetStripCustomerId
        {
            get
            {
                if (Session["StripeCustomerId"] != null)
                    return Session["StripeCustomerId"].ToString();
                else
                {
                    var currentUser = _userService.GetAllUsers().Where(c => c.Id == Infrastructure.Authentication.CurrentUserId).FirstOrDefault();
                    Session["StripeCustomerId"] = currentUser.StripecustomerId;
                    return currentUser.StripecustomerId;
                }
            }
        }

        public ActionResult Index(DealerCarViewModel model = null)
        {

            CheckCurrentUserSubscribedOrNot();
            return View(model);
        }

        #region Left Side Search Criteria
        public ActionResult MiniSearch(CarFilterViewModel args)
        {
            var model = _dealerCarService.PrepareDealarCarViewModel();
            return PartialView("_LeftSideSearchPanel", model);
        }

        #endregion

        #region Add and Update Car
        public ActionResult AddUpdateCar(string Cid)
        {

            CheckCurrentUserSubscribedOrNot();

            int CId = 0;
            if (!string.IsNullOrEmpty(Cid))
                CId = int.Parse(EncryptDecryptHelper.Decrypt(Cid));
            var model = _dealerCarService.PrepareDealarCarViewModel(CId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUpdateCar(DealerCarViewModel model)
        {
            CheckCurrentUserSubscribedOrNot();

            model.AppUserId = Infrastructure.Authentication.CurrentUserId;
            var result = _dealerCarService.AddOrUpdateCar(model);

            return RedirectToAction("Index");
        }

        #endregion

        #region Delete Car Images

        [HttpPost]
        public ActionResult DeleteCarImage(string imageId)
        {
            ProcessViewModel resultmodel = new ProcessViewModel();
            resultmodel = _dealerCarService.DeleteCarImage(imageId);
            return new JsonResult() { Data = new { status = resultmodel.IsSuccess, message = resultmodel.Message }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        #endregion


        #region Add or Update Dealer Car Comment        
        public ActionResult AddUpdateCarComment(DealerCommentNRatingViewModel dealerCommentVM)
        {
            dynamic showMessageString = string.Empty;

Presentation/Trialcar.Web/Controllers/SearchController.cs
using Incite.Core.Domain;
using Incite.Core.Infrastructure;
using Incite.Data.Repositories;
using Incite.Services;
using Incite.Services.ViewModels;
using PagedList;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trialcar.Web.Helper;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _DealerCarService;
        private readonly ICarSearchService _CarSearchService;
        private readonly IPaymentService _paymentService;
        private readonly IUsersService _userService;
       
        #endregion
        #region ctor
        public SearchController(IDealerCarService dealerCarService, ICarSearchService carSearchService
            , IUsersService usersService, IPaymentService paymentService)
        {
            _DealerCarService = dealerCarService;
            _CarSearchService = carSearchService;
            _paymentService = paymentService;
            _userService = usersService;
        }
        #endregion


        private void CheckCurrentUserSubscribedOrNot()
        {
            ViewBag.IsSubscribed = false;

            if (!Infrastructure.Authentication.IsAdmin)
            {
                var currentUser = _userService.GetAllUsers().Where(c => c.Id == Infrastructure.Authentication.CurrentUserId).FirstOrDefault();
                //ViewBag.IsSubscribed = currentUser.IsSubscribed;
                if (string.IsNullOrEmpty(currentUser.StripecustomerId))
                    ViewBag.IsSubscribed = false;
                else
                {
                    Customer customer = new Customer();
                    try
                    {
                        customer = _paymentService.GetCustomer(currentUser.StripecustomerId);
                        ViewBag.IsSubscribed = customer.Subscriptions.Count() > 0;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.IsSubscribed = false;
                    }

                }
            }
        }



        public string GetStripCustomerId
        {
            get
            {
                if (Session["StripeCustomerId"] != null)
                    return Session["StripeCustomerId"].ToString();
                else
                {
                    var currentUser = _userService.GetAllUsers().Where(c => c.Id == Infrastructure.Authentication.CurrentUserId).FirstOrDefault();
                    Session["StripeCustomerId"] = currentUser.StripecustomerId;
                    return currentUser.StripecustomerId;
                }
            }
        }



        // GET: Search
        public ActionResult SearchResult()
        {
            CheckCurrentUserSubscribedOrNot();
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult HomeFilter()
        {
            var model = _CarSearchService.PrepareHomeCareFilter();
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult SearchLeftFilter(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareHomeCareFilter(request);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult MygarageLeftFilter(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareHomeCareFilter(request);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult CarlistSortBy(CarFilterViewModel request)
        {
            var model = _CarSearchService.PrepareSortby(request);
            return PartialView(model);
        }
        #region Car Listing
        [ChildActionOnly]
        public PartialViewResult CarListingView(CarFilterViewModel args, bool IsDealerSearch, int dealerId = 0, bool IsSold = false, int Page = 1)
        {
            IPagedList<DealerCarDetails> lst = null;
            AppUsers appUsers = null;
            appUsers = _DealerCarService.getUserById(dealerId);
            long currentUserId;
            if (dealerId > 0)
            {
                currentUserId = dealerId;
            }
            else
            {
                currentUserId = Infrastructure.Authentication.CurrentUserId ?? default(int);
            }

            ViewBag.IsPaymetList = true;
            var userProfile = _userService.GetUserProfile(Convert.ToInt32(currentUserId));
            var userpaymentList = _paymentService.GetUserPaymentSourceList(userProfile.User.Email);
            if (userpaymentList != null && userpaymentList.Data != null && userpaymentList.Count() > 0)
            {
                ViewBag.IsPaymetList = false;
            }



            var model = _DealerCarService.GetDealerCarListing(currentUserId, args, IsDealerSearch, IsSold);

            lst = model.ToPagedList(Page, (int)SiteEnum.PageSetting.PageSize);
            return PartialView(Tuple.Create(lst, appUsers));
        }
        #endregion
    }
}

Presentation/Trialcar.Web/Controllers/SharedController.cs
using Incite.Services;
using Incite.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Incite.Core.Domain;
using Incite.Core.Infrastructure;

namespace Trialcar.Web.Controllers
{
    [Authorize]
    public class SharedController : Controller
    {
        #region  Private Member Variables
        private readonly IDealerCarService _dealerCarService;
        private readonly IUsersService _userService;
        private readonly IPaymentService _paymentService;

        #endregion

        public SharedController(IUsersService usersService, IDealerCarService DealerCarService, IPaymentService paymentService)
        {
            _userService = usersService;
            _dealerCarService = DealerCarService;
            _paymentService = paymentService;
        }

       

        #region Car Listing
        public PartialViewResult CarListing(CarFilterViewModel args, bool IsDealerSearch, int dealerId = 0, bool IsSold = false, int Page = 1)
        {
            IPagedList<DealerCarDetails> lst = null;
            AppUsers appUsers = _dealerCarService.getUserById(dealerId);
            long currentUserId;
            if (dealerId > 0)
            {
                currentUserId = dealerId;
            } else
            {
                currentUserId = Infrastructure.Authentication.CurrentUserId ?? default(int);
            }

            ViewBag.IsPaymetList = true;
            var userProfile = _userService.GetUserProfile(Convert.ToInt32(currentUserId));
            var userpaymentList = _paymentService.GetUserPaymentSourceList(userProfile.User.Email);
            if(userpaymentList != null && userpaymentList.Data != null && userpaymentList.Count() > 0)
            {
                ViewBag.IsPaymetList = false;
            }
            


            var model = _dealerCarService.GetDealerCarListing(currentUserId, args, IsDealerSearch, IsSold);

            lst = model.ToPagedList(Page, (int)SiteEnum.PageSetting.PageSize);
            return PartialView("_CarListing", Tuple.Create(lst, appUsers));
        }
        #endregion

        public PartialViewResult ProfileImagePartial(string usrImage)
        {
            return PartialView("_ProfileImagePartial", usrImage);

        }
    }

   
    }

Presentation/Trialcar.Web/Views/DealerCar/BuyNowHoldNowDetail.cshtml
@using Incite.Services.ViewModels
@using System.Web.Configuration;
@model BuyNowHoldNowDetailViewModel
@using Trialcar.Web.Infrastructure;
@using Incite.Core.Infrastructure;
﻿@using Incite.Core.Extention
@{
    Layout = null;
    decimal transactionFee = ((Model.Price * 0.5M) / 100) + 5;
    decimal totalPrice = Model.Price + transactionFee;

    var dealerCar = AppExtentionHelper.GetDealerCarByDealerCarId(Model.DealerCarDetailId);
    var HoldPercentage = (decimal)int.Parse(WebConfigurationManager.AppSettings["OnHoldPaymentPerc"]);
    var HoldValue = dealerCar.Price * (HoldPercentage / 100);
    var fee = (decimal)0.05 * HoldValue;

    if (fee < 5)
    {
        fee = 5;
    }

    List<SelectListItem> paymenTypes = (List<SelectListItem>)ViewBag.PaymentTypes;

}
@{

    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
<div class="col-md-12 col-sm-6">
    <div id="dvLoginMsg" class="alert alert-info dvdismiss" style="display:none;">

    </div>
    @using (Html.BeginForm("BuyNowHoldNowDetail", "DealerCar", FormMethod.Post, new { @class = "form-horizontal", id = "BuyNowHoldNowDetailForm" }))
    {

        @Html.AntiForgeryToken()


        <div class="col-md-12 col-sm-6">
            @Html.HiddenFor(m => m.DealerCarDetailId)
            @Html.HiddenFor(m => m.IsOnHold)
            @*@if (Model.PaymentTypes != null)*@
            @if (paymenTypes.Count > 0)
            {

                <div class="form-group">
                    <label for="example-email" class="col-md-12">Payment Mode</label>
                    @*@Html.DropDownListFor(m => m.PaymentTypeId
                        , new SelectList(Model.PaymentTypes, "Id", "PaymentType", Model.PayId)
                        , "Select Payment Mode"
                        , new { @id = "drpPayment", @class = "form-control" })*@
                    @Html.DropDownListFor(m => m.PaymentTypeId, paymenTypes, new { @id = "drpPayment", @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PaymentTypeId, string.Empty, new { @class = "text-danger" })
                </div>

                <br />
                if (Model.Price > 0)
                {
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Car Price:</label>
                        <div class="col-md-7">
                            $@Model.Price.ToString("#,##0")
                        </div>

                    </div>
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Transaction Fee:</label>
                        <div class="col-md-7">
                            $@transactionFee.ToString("#,##0")
                        </div>
                    </div>
                    <div class="modal - footer text - center"></div>
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Total Price:</label>
                        <div class="col-md-7">
                            $@totalPrice.ToString("#,##0")
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Car Price:</label>
                        <div class="col-md-7">
                            $@dealerCar.Price.ToString("#,##0")
                        </div>

                    </div>
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Hold-Now Percentage:</label>
                        <div class="col-md-7">
                            $@HoldPercentage%
                        </div>
                    </div>
                    <div class="modal - footer text - center"></div>
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Convinience Fee:</label>
                        <div class="col-md-7">
                            $@fee.ToString("#,##0")
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="example-email" class="col-md-3">Hold-Now Total:</label>
                        <div class="col-md-7">
                            $@((HoldValue + fee).ToString("#,##0"))
                        </div>
                    </div>

                }
                <br /><br />

                <div class="raw form-group">
                    @*<input type="button" onclick="buynowclick();" value="Confirm" name="bynowConfirm" class="btn btn-success" />*@
                    <input type="submit" value="Confirm" name="bynowConfirm" class="btn btn-success" />
                </div>

            }

        </div>

    }

    @if (paymenTypes.Count <= 0)
    {
        <div class="form-group">
            <h6 style="width: 588px;float: left;font-weight: normal;">
                To facilitate lower transaction fees, Dealer Inventory Network only allows Bank Accounts to make a purchase.
            </h6>
            <h6 style="width: 588px;font-weight: normal;text-align: center;">
                Please <a href="/Account/UpdateSettings">Click Here</a> to add/verify your bank account.
            </h6>
        </div>
    }
</div>



@*<script type="text/javascript">
    function buynowclick() {
        debugger;
        var fd = new FormData();
        var drppamentvalue = $("#drpPayment").val();
        var Delarcarid = $("#DealerCarDetailId").val();
        var ishold = $("#IsOnHold").val();
        if (drppamentvalue != "Select Payment Mode" && drppamentvalue != "") {
            fd.append("DealerCarDetailId", Delarcarid);
            fd.append("IsOnHold", ishold);
            fd.append("PaymentTypeId", drppamentvalue);
            fd.append("StripePaymentId", drppamentvalue);

            $.ajax(
                {

                    type: "POST",
                    url: "/Dealer/BuyNowHoldNowDetail",
                    data: fd,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        paymentsucess(data)
                    },
                    complete: function () {

                    }
                }
            );

        }
        else {
            alert("Select Payment Mode")
        }

    }
    function paymentsucess(data) {

        if (data.IsSuccess == true) {
            alert(data.Message);
            window.location.reload();
        }
        else {
            alert(data.Message);
        }
    }
</script>*@

Presentation/Trialcar.Web/Views/DealerCar/DealerDetail.cshtml
@model Incite.Core.Domain.AppUsers
@{
    ViewBag.Title = "Dealer Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Display car comments-->
@Html.Partial("_DealerCarCommentPartial", Model)
<!--/Display car comments-->
<!--Listing-->
<section class="listing-page">
    <div class="container">
        <div class="row">
            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, dealerId = Model.Id });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @{Html.RenderAction("SearchLeftFilter", "Search"); }
            <!--Left Side Bar-->
        </div>
    </div>
</section>
<!-- /Listing-->
@*Styles.Render("~/Assets/Trialcars/css/fxss-rate.css")
@Scripts.Render("~/Assets/Trialcars/js/fxss-rate-iconfont.js")
@Scripts.Render("~/Assets/Trialcars/js/fxss-rate.js")
@{
    float totRating = 0.0F, count = 0.0F;
    double avgRating = 0.0;
    if (Model.DealerComments.Count > 0)
    {
        foreach (var item in @Model.DealerComments)
        {
            totRating += item.Rating;
            count++;

        }
        avgRating = Math.Round((totRating / count), 1);
    }
}
<script>
    $(".rating-container").rate({
        length: 5,
        value: @avgRating,
        readonly: true,
        size: '30px',
        text: false
    });
</script>*@ 

Presentation/Trialcar.Web/Views/DealerCar/DealerSoldCar.cshtml
@model Incite.Services.ViewModels.DealerCarViewModel
@using Incite.Core.Extention
@using Incite.Core.Infrastructure
@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Page Header-->
<section class="page-header soldcar">
    <div class="container">
        <div class="page-header_wrap">
            <div class="page-heading">
                <h1>My Sold Car</h1>
            </div>
            <ul class="coustom-breadcrumb">
                <li><a href="@Url.RouteUrl("HomeIndex")">Home</a></li>
                <li>My Sold Car</li>
            </ul>
        </div>
    </div>
    <!-- Dark Overlay-->
    <div class="dark-overlay"></div>
</section>
<!-- /Page Header -->

<section class="listing-page">
    <div class="container">
        <div class="row">
            <div class="row form-group">
                <div class="col-sm-12 text-right">
                    @*<a href="/AddCarInGarage/" class="btn">Add Car</a>*@
                </div>
            </div>
            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, IsSold = true });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @*@{Html.RenderAction("MygarageLeftFilter", "Search"); }*@
            <!--Left Side Bar-->
        </div>
    </div>
</section>

Presentation/Trialcar.Web/Views/DealerCar/Index.cshtml
@model Incite.Services.ViewModels.DealerCarViewModel
@using Incite.Core.Extention
@using Incite.Core.Infrastructure


@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="page-header compare_page">

    <div class="container">

        <div class="page-header_wrap">
            <div class="page-heading">
                <h1>My Garage</h1>
            </div>
        </div>
    </div>
    <!-- Dark Overlay-->
    <div class="dark-overlay"></div>
</section>

<section class="listing-page">
    <div class="container">
        <div class="row">
            <div class="row form-group">
                <div class="col-sm-12 text-right">
                    <a href="/AddCarInGarage/" class="btn">Add Car</a>
                </div>
                <div class="col-sm-12 text-center" style="display:none">
                    <p style="color:red">Enter your KYC/Bank Information for your cars to be able to search/buy/hold/visible a car at lower rates</p>
                </div>
            </div>

            <!--Listing-->
            @{Html.RenderAction("CarListing", "Shared", new { IsDealerSearch = true, IsSold = false });}
            <!-- Listing-->
            <!--Left Side Bar-->
            @{Html.RenderAction("MygarageLeftFilter", "Search"); }
            <!--Left Side Bar-->

        </div>
    </div>
</section>

Presentation/Trialcar.Web/Views/DealerCar/_AddDealerComment.cshtml
@model Incite.Services.ViewModels.DealerCommentNRatingViewModel

<div>
    @using (Ajax.BeginForm("AddUpdateCarComment", "DealerCar", new AjaxOptions { HttpMethod = "POST", OnSuccess = "addCommentSuccess", OnFailure = "alert('Error Occured while Rating.')" }))
    {
        @Html.HiddenFor(m => m.Rating, new { @id = "dealerCarRating" })
        @Html.HiddenFor(m => m.RatingForDealerId)
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.CommentReply)
        <!-- Rating Stars Box -->
        <div class='rating-stars'>
            <ul id='stars'>
                <li class='star' title='Poor' data-value='1'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Fair' data-value='2'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Good' data-value='3'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Very Good' data-value='4'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
                <li class='star' title='Excellent' data-value='5'>
                    <i class='fa fa-star fa-fw'></i>
                </li>
            </ul>
        </div>
        <div style="clear:both"></div>
        <div>
            <div class="div-float-left" style="width: 350px">@Html.TextAreaFor(m => m.Comment, new { @rows = 2, @class = "form-control", @style= "max-height: 100px; min-width: 350px; max-width: 350px; min-height: 70px; " })</div>
            <div class="comm_btn_div"><input type="submit" class="commentbtn btn" value="Go!"></div>
        </div>
        <div style="clear:both"></div>
    }
    <!--Display Dealer Car Comments-->
    <span class="CarCommentResult"></span>
    <!--/Display Dealer Car Comments-->
</div>
    

Presentation/Trialcar.Web/Views/DealerCar/_AddDealerCommentReply.cshtml
@model Incite.Services.ViewModels.DealerCommentNRatingViewModel
@using (Ajax.BeginForm("AddUpdateCarCommentReply", "DealerCar", new AjaxOptions { HttpMethod = "POST", OnSuccess = "addCommentSuccess", OnFailure = "alert('Error Occured while Reply.')" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Comment)
    @Html.HiddenFor(m => m.Rating)
    @Html.HiddenFor(m => m.RatingForDealerId)
    @Html.HiddenFor(m => m.CreatedTs)

    <input type="hidden" name="DealerId" value="@Model.DealerId" />
    <div class="div-float-left">@Html.TextAreaFor(m => m.CommentReply, new { @rows = 2, @class = "form-control" })</div>
    <div class="comm_btn_div"><input type="submit" class="commentbtn btn" value="Reply"></div>
    <div style="clear:both"></div>
}
<!--Display Dealer Car Comments-->
<span class="CarCommentResult"></span>
<!--/Display Dealer Car Comments-->